using SGE.Model.Entidades.Interfaces;
using System;
namespace SGE.Model.Entidades
{
    public class Reportes_PPP //: IReportes_PPP
    {
        #region Primitive Properties

        public Int64 ID_FICHA { get; set; }
        public string APELLIDO { get; set; }
        public string NOMBRE { get; set; }
        public string CUIL { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public DateTime FER_NAC { get; set; }
        public string CALLE { get; set; }
        public string NUMERO { get; set; }
        public string PISO { get; set; }
        public string DPTO { get; set; }
        public string MONOBLOCK { get; set; }
        public string PARCELA { get; set; }
        public string MANZANA { get; set; }
        public string ENTRECALLES { get; set; }
        public string BARRIO { get; set; }
        public string CODIGO_POSTAL { get; set; }
        public Int64? ID_LOCALIDAD { get; set; }
        public string N_LOCALIDAD { get; set; }
        public Decimal? ID_DPTO { get; set; }
        public string N_DEPARTAMENTO { get; set; }
        public string TEL_FIJO { get; set; }
        public string TEL_CELULAR { get; set; }
        public string CONTACTO { get; set; }
        public string MAIL { get; set; }
        public string TIENE_HIJOS { get; set; }
        public Int64 CANTIDAD_HIJOS { get; set; }
        public string ES_DISCAPACITADO { get; set; }
        public string TIENE_DEF_MOTORA { get; set; }
        public string TIENE_DEF_MENTAL { get; set; }
        public string TIENE_DEF_SENSORIAL { get; set; }
        public string TIENE_DEF_PSICOLOGICA { get; set; }
        public string DEFICIENCIA_OTRA { get; set; }
        public string CERTIF_DISCAP { get; set; }
        public string SEXO { get; set; }
        public Int64 TIPO_FICHA { get; set; }
        public Int64 ESTADO_CIVIL { get; set; }
        public DateTime? FEC_SIST { get; set; }
        public string ORIGEN_CARGA { get; set; }
        public string NRO_TRAMITE { get; set; }
        public Int64? ID_CAJA { get; set; }
        public Int64? ID_TIPO_RECHAZO { get; set; }
        public string N_TIPO_RECHAZO { get; set; }
        public Int64? ID_EST_FIC { get; set; }
        public string N_ESTADO_FICHA { get; set; }
        public string NIVEL_ESCOLARIDAD { get; set; }
        public Int64? MODALIDAD { get; set; }
        public string TAREAS { get; set; }
        public string ALTA_TEMPRANA { get; set; }
        public DateTime? AT_FECHA_INICIO { get; set; }
        public DateTime? AT_FECHA_CESE { get; set; }
        public Int64? ID_MOD_CONT_AFIP { get; set; }
        public string MOD_CONT_AFIP { get; set; }
        public DateTime? FEC_MODIF { get; set; }
        public Int64? ID_EMP { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string EMP_CUIT { get; set; }
        public string COD_ACT { get; set; }
        public Int64? CANT_EMP { get; set; }
        public string EMP_CALLE { get; set; }
        public string EMP_NUMERO { get; set; }
        public string EMP_PISO { get; set; }
        public string EMP_DPTO { get; set; }
        public string EMP_CP { get; set; }
        public Int64? ID_LOC { get; set; }
        public string EMP_N_LOCALIDAD { get; set; }
        public string EMP_N_DEPARTAMENTO { get; set; }
        public string EMP_CELULAR { get; set; }
        public string EMP_MAIL { get; set; }
        public string EMP_ES_COOPERATIVA { get; set; }
        public Int64? EU_ID_USUARIO { get; set; }
        public string EU_NOMBRE { get; set; }
        public string EMP_APELLIDO { get; set; }
        public string EU_MAIL { get; set; }
        public string EU_TELEFONO { get; set; }
        public Int64? ID_BENEFICIARIO { get; set; }
        public Int64? BEN_ID_ESTADO { get; set; }
        public string BEN_N_ESTADO { get; set; }
        public Int64? BEN_NRO_CTA { get; set; }
        public Int64? BEN_ID_SUCURSAL { get; set; }
        public string BEN_COD_SUC { get; set; }
        public string BEN_SUCURSAL { get; set; }
        public DateTime? BEN_FEC_SOL_CTA { get; set; }
        public string NOTIFICADO { get; set; }
        public DateTime? FEC_NOTIF { get; set; }
        public DateTime? BEN_FEC_INICIO { get; set; }
        public DateTime? BEN_FEC_BAJA { get; set; }
        public string TIENE_APODERADO { get; set; }
        public Int64? ID_APODERADO { get; set; }
        public string APO_APELLIDO { get; set; }
        public string APO_NOMBRE { get; set; }
        public string APO_DNI { get; set; }
        public string APO_CUIL { get; set; }
        public string APO_SEXO { get; set; }
        public Int64? APO_NRO_CTA { get; set; }
        public Int64? APO_ID_SUC { get; set; }
        public string APO_COD_SUC { get; set; }
        public string APO_SUCURSAL { get; set; }
        public DateTime? APO_FEC_SOL_CTA { get; set; }
        public DateTime? APO_FEC_NAC { get; set; }
        public string APO_CALLE { get; set; }
        public string APO_NRO { get; set; }
        public string APO_PISO { get; set; }
        public string APO_MONOBLOCK { get; set; }
        public string APO_DPTO { get; set; }
        public string APO_PARCELA { get; set; }
        public string APO_MANZANA { get; set; }
        public string APO_ENTRE_CALLES { get; set; }
        public string APO_BARRIO { get; set; }
        public string APO_CP { get; set; }
        public Int64? APO_ID_LOC { get; set; }
        public string APO_LOCALIDAD { get; set; }
        public Decimal? APO_ID_DEPTO { get; set; }
        public string APO_DEPARTAMENTO { get; set; }
        public string APO_TELEFONO { get; set; }
        public string APO_CELULAR { get; set; }
        public string APO_EMAIL { get; set; }
        public Int64? IDETAPA { get; set; }
        public Int64? AP_ID_ESTADO { get; set; }
        public string AP_N_ESTADO { get; set; }
        public Int64? ID_SUBPROGRAMA { get; set; }
        public string SUBPROGRAMA { get; set; }
        public Int64? TIPO_PPP { get; set; }
        public string SEDE_ROTATIVA { get; set; }
        public string HORARIO_ROTATIVO { get; set; }
        public string N_DESCRIPCION_T { get; set; }
        public string N_CURSADO_INS { get; set; }
        public DateTime? EGRESO { get; set; }
        public string COD_USO_INTERNO { get; set; }
        public string CARGA_HORARIA { get; set; }
        public string CH_CUAL { get; set; }
        public Int64? ID_CARRERA { get; set; }
        public string N_CARRERA { get; set; }
        public Int64? ID_INSTITUCION { get; set; }
        public string N_INSTITUCION { get; set; }
        public string CONSTANCIA_EGRESO { get; set; }
        public string MATRICULA { get; set; }
        public string CONSTANCIA_CURSO { get; set; }


        #endregion
    }
}
