//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("GE", "T_BENEFICIARIOS_T_ESTADOS_FK1", "T_ESTADOS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SGE.Importador.Datos.T_ESTADOS), "T_BENEFICIARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SGE.Importador.Datos.T_BENEFICIARIOS), true)]
[assembly: EdmRelationshipAttribute("GE", "T_BENEFICIARIOS_T_FICHAS_FK1", "T_FICHAS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SGE.Importador.Datos.T_FICHAS), "T_BENEFICIARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SGE.Importador.Datos.T_BENEFICIARIOS), true)]
[assembly: EdmRelationshipAttribute("GE", "T_CUENTAS_BANCO_T_BENEFIC_FK1", "T_BENEFICIARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGE.Importador.Datos.T_BENEFICIARIOS), "T_CUENTAS_BANCO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SGE.Importador.Datos.T_CUENTAS_BANCO), true)]
[assembly: EdmRelationshipAttribute("GE", "T_CUENTAS_BANCO_MONEDA_FK", "T_TABLAS_BCO_CBA", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SGE.Importador.Datos.T_TABLAS_BCO_CBA), "T_CUENTAS_BANCO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SGE.Importador.Datos.T_CUENTAS_BANCO), true)]
[assembly: EdmRelationshipAttribute("GE", "T_CUENTAS_BANCO_SISTEMAFK1", "T_TABLAS_BCO_CBA", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SGE.Importador.Datos.T_TABLAS_BCO_CBA), "T_CUENTAS_BANCO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SGE.Importador.Datos.T_CUENTAS_BANCO), true)]
[assembly: EdmRelationshipAttribute("GE", "T_CUENTAS_BANCO_SUCURSAL__FK1", "T_TABLAS_BCO_CBA", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SGE.Importador.Datos.T_TABLAS_BCO_CBA), "T_CUENTAS_BANCO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SGE.Importador.Datos.T_CUENTAS_BANCO), true)]
[assembly: EdmRelationshipAttribute("GE", "T_TABLAS_BCO_CBA_T_TIPOS__FK1", "T_TIPOS_TABLA_BCO_CBA", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SGE.Importador.Datos.T_TIPOS_TABLA_BCO_CBA), "T_TABLAS_BCO_CBA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SGE.Importador.Datos.T_TABLAS_BCO_CBA), true)]

#endregion

namespace SGE.Importador.Datos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class GEContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto GEContainer usando la cadena de conexión encontrada en la sección 'GEContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public GEContainer() : base("name=GEContainer", "GEContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto GEContainer.
        /// </summary>
        public GEContainer(string connectionString) : base(connectionString, "GEContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto GEContainer.
        /// </summary>
        public GEContainer(EntityConnection connection) : base(connection, "GEContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<T_BENEFICIARIOS> T_BENEFICIARIOS
        {
            get
            {
                if ((_T_BENEFICIARIOS == null))
                {
                    _T_BENEFICIARIOS = base.CreateObjectSet<T_BENEFICIARIOS>("T_BENEFICIARIOS");
                }
                return _T_BENEFICIARIOS;
            }
        }
        private ObjectSet<T_BENEFICIARIOS> _T_BENEFICIARIOS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<T_CUENTAS_BANCO> T_CUENTAS_BANCO
        {
            get
            {
                if ((_T_CUENTAS_BANCO == null))
                {
                    _T_CUENTAS_BANCO = base.CreateObjectSet<T_CUENTAS_BANCO>("T_CUENTAS_BANCO");
                }
                return _T_CUENTAS_BANCO;
            }
        }
        private ObjectSet<T_CUENTAS_BANCO> _T_CUENTAS_BANCO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<T_ESTADOS> T_ESTADOS
        {
            get
            {
                if ((_T_ESTADOS == null))
                {
                    _T_ESTADOS = base.CreateObjectSet<T_ESTADOS>("T_ESTADOS");
                }
                return _T_ESTADOS;
            }
        }
        private ObjectSet<T_ESTADOS> _T_ESTADOS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<T_FICHAS> T_FICHAS
        {
            get
            {
                if ((_T_FICHAS == null))
                {
                    _T_FICHAS = base.CreateObjectSet<T_FICHAS>("T_FICHAS");
                }
                return _T_FICHAS;
            }
        }
        private ObjectSet<T_FICHAS> _T_FICHAS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<T_TABLAS_BCO_CBA> T_TABLAS_BCO_CBA
        {
            get
            {
                if ((_T_TABLAS_BCO_CBA == null))
                {
                    _T_TABLAS_BCO_CBA = base.CreateObjectSet<T_TABLAS_BCO_CBA>("T_TABLAS_BCO_CBA");
                }
                return _T_TABLAS_BCO_CBA;
            }
        }
        private ObjectSet<T_TABLAS_BCO_CBA> _T_TABLAS_BCO_CBA;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<T_TIPOS_TABLA_BCO_CBA> T_TIPOS_TABLA_BCO_CBA
        {
            get
            {
                if ((_T_TIPOS_TABLA_BCO_CBA == null))
                {
                    _T_TIPOS_TABLA_BCO_CBA = base.CreateObjectSet<T_TIPOS_TABLA_BCO_CBA>("T_TIPOS_TABLA_BCO_CBA");
                }
                return _T_TIPOS_TABLA_BCO_CBA;
            }
        }
        private ObjectSet<T_TIPOS_TABLA_BCO_CBA> _T_TIPOS_TABLA_BCO_CBA;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet T_BENEFICIARIOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToT_BENEFICIARIOS(T_BENEFICIARIOS t_BENEFICIARIOS)
        {
            base.AddObject("T_BENEFICIARIOS", t_BENEFICIARIOS);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet T_CUENTAS_BANCO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToT_CUENTAS_BANCO(T_CUENTAS_BANCO t_CUENTAS_BANCO)
        {
            base.AddObject("T_CUENTAS_BANCO", t_CUENTAS_BANCO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet T_ESTADOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToT_ESTADOS(T_ESTADOS t_ESTADOS)
        {
            base.AddObject("T_ESTADOS", t_ESTADOS);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet T_FICHAS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToT_FICHAS(T_FICHAS t_FICHAS)
        {
            base.AddObject("T_FICHAS", t_FICHAS);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet T_TABLAS_BCO_CBA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToT_TABLAS_BCO_CBA(T_TABLAS_BCO_CBA t_TABLAS_BCO_CBA)
        {
            base.AddObject("T_TABLAS_BCO_CBA", t_TABLAS_BCO_CBA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet T_TIPOS_TABLA_BCO_CBA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToT_TIPOS_TABLA_BCO_CBA(T_TIPOS_TABLA_BCO_CBA t_TIPOS_TABLA_BCO_CBA)
        {
            base.AddObject("T_TIPOS_TABLA_BCO_CBA", t_TIPOS_TABLA_BCO_CBA);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GE", Name="T_BENEFICIARIOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_BENEFICIARIOS : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto T_BENEFICIARIOS.
        /// </summary>
        /// <param name="iD_BENEFICIARIO">Valor inicial de la propiedad ID_BENEFICIARIO.</param>
        public static T_BENEFICIARIOS CreateT_BENEFICIARIOS(global::System.Int32 iD_BENEFICIARIO)
        {
            T_BENEFICIARIOS t_BENEFICIARIOS = new T_BENEFICIARIOS();
            t_BENEFICIARIOS.ID_BENEFICIARIO = iD_BENEFICIARIO;
            return t_BENEFICIARIOS;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_BENEFICIARIO
        {
            get
            {
                return _ID_BENEFICIARIO;
            }
            set
            {
                if (_ID_BENEFICIARIO != value)
                {
                    OnID_BENEFICIARIOChanging(value);
                    ReportPropertyChanging("ID_BENEFICIARIO");
                    _ID_BENEFICIARIO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_BENEFICIARIO");
                    OnID_BENEFICIARIOChanged();
                }
            }
        }
        private global::System.Int32 _ID_BENEFICIARIO;
        partial void OnID_BENEFICIARIOChanging(global::System.Int32 value);
        partial void OnID_BENEFICIARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_FICHA
        {
            get
            {
                return _ID_FICHA;
            }
            set
            {
                OnID_FICHAChanging(value);
                ReportPropertyChanging("ID_FICHA");
                _ID_FICHA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_FICHA");
                OnID_FICHAChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_FICHA;
        partial void OnID_FICHAChanging(Nullable<global::System.Int32> value);
        partial void OnID_FICHAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ID_PROGRAMA
        {
            get
            {
                return _ID_PROGRAMA;
            }
            set
            {
                OnID_PROGRAMAChanging(value);
                ReportPropertyChanging("ID_PROGRAMA");
                _ID_PROGRAMA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_PROGRAMA");
                OnID_PROGRAMAChanged();
            }
        }
        private Nullable<global::System.Int16> _ID_PROGRAMA;
        partial void OnID_PROGRAMAChanging(Nullable<global::System.Int16> value);
        partial void OnID_PROGRAMAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ID_ESTADO
        {
            get
            {
                return _ID_ESTADO;
            }
            set
            {
                OnID_ESTADOChanging(value);
                ReportPropertyChanging("ID_ESTADO");
                _ID_ESTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_ESTADO");
                OnID_ESTADOChanged();
            }
        }
        private Nullable<global::System.Int16> _ID_ESTADO;
        partial void OnID_ESTADOChanging(Nullable<global::System.Int16> value);
        partial void OnID_ESTADOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FEC_ALTA
        {
            get
            {
                return _FEC_ALTA;
            }
            set
            {
                OnFEC_ALTAChanging(value);
                ReportPropertyChanging("FEC_ALTA");
                _FEC_ALTA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FEC_ALTA");
                OnFEC_ALTAChanged();
            }
        }
        private Nullable<global::System.DateTime> _FEC_ALTA;
        partial void OnFEC_ALTAChanging(Nullable<global::System.DateTime> value);
        partial void OnFEC_ALTAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FEC_MODIF
        {
            get
            {
                return _FEC_MODIF;
            }
            set
            {
                OnFEC_MODIFChanging(value);
                ReportPropertyChanging("FEC_MODIF");
                _FEC_MODIF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FEC_MODIF");
                OnFEC_MODIFChanged();
            }
        }
        private Nullable<global::System.DateTime> _FEC_MODIF;
        partial void OnFEC_MODIFChanging(Nullable<global::System.DateTime> value);
        partial void OnFEC_MODIFChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_USUARIO_MODIF
        {
            get
            {
                return _ID_USUARIO_MODIF;
            }
            set
            {
                OnID_USUARIO_MODIFChanging(value);
                ReportPropertyChanging("ID_USUARIO_MODIF");
                _ID_USUARIO_MODIF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_USUARIO_MODIF");
                OnID_USUARIO_MODIFChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_USUARIO_MODIF;
        partial void OnID_USUARIO_MODIFChanging(Nullable<global::System.Int32> value);
        partial void OnID_USUARIO_MODIFChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_USUARIO_ALTA
        {
            get
            {
                return _ID_USUARIO_ALTA;
            }
            set
            {
                OnID_USUARIO_ALTAChanging(value);
                ReportPropertyChanging("ID_USUARIO_ALTA");
                _ID_USUARIO_ALTA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_USUARIO_ALTA");
                OnID_USUARIO_ALTAChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_USUARIO_ALTA;
        partial void OnID_USUARIO_ALTAChanging(Nullable<global::System.Int32> value);
        partial void OnID_USUARIO_ALTAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RESIDENTE
        {
            get
            {
                return _RESIDENTE;
            }
            set
            {
                OnRESIDENTEChanging(value);
                ReportPropertyChanging("RESIDENTE");
                _RESIDENTE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RESIDENTE");
                OnRESIDENTEChanged();
            }
        }
        private global::System.String _RESIDENTE;
        partial void OnRESIDENTEChanging(global::System.String value);
        partial void OnRESIDENTEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NACIONALIDAD
        {
            get
            {
                return _NACIONALIDAD;
            }
            set
            {
                OnNACIONALIDADChanging(value);
                ReportPropertyChanging("NACIONALIDAD");
                _NACIONALIDAD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NACIONALIDAD");
                OnNACIONALIDADChanged();
            }
        }
        private Nullable<global::System.Int32> _NACIONALIDAD;
        partial void OnNACIONALIDADChanging(Nullable<global::System.Int32> value);
        partial void OnNACIONALIDADChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TIPO_PERSONA
        {
            get
            {
                return _TIPO_PERSONA;
            }
            set
            {
                OnTIPO_PERSONAChanging(value);
                ReportPropertyChanging("TIPO_PERSONA");
                _TIPO_PERSONA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TIPO_PERSONA");
                OnTIPO_PERSONAChanged();
            }
        }
        private global::System.String _TIPO_PERSONA;
        partial void OnTIPO_PERSONAChanging(global::System.String value);
        partial void OnTIPO_PERSONAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> COD_ACT_BANCARIO
        {
            get
            {
                return _COD_ACT_BANCARIO;
            }
            set
            {
                OnCOD_ACT_BANCARIOChanging(value);
                ReportPropertyChanging("COD_ACT_BANCARIO");
                _COD_ACT_BANCARIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COD_ACT_BANCARIO");
                OnCOD_ACT_BANCARIOChanged();
            }
        }
        private Nullable<global::System.Int32> _COD_ACT_BANCARIO;
        partial void OnCOD_ACT_BANCARIOChanging(Nullable<global::System.Int32> value);
        partial void OnCOD_ACT_BANCARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> COD_NAT_JURIDICA
        {
            get
            {
                return _COD_NAT_JURIDICA;
            }
            set
            {
                OnCOD_NAT_JURIDICAChanging(value);
                ReportPropertyChanging("COD_NAT_JURIDICA");
                _COD_NAT_JURIDICA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COD_NAT_JURIDICA");
                OnCOD_NAT_JURIDICAChanged();
            }
        }
        private Nullable<global::System.Int32> _COD_NAT_JURIDICA;
        partial void OnCOD_NAT_JURIDICAChanging(Nullable<global::System.Int32> value);
        partial void OnCOD_NAT_JURIDICAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CONDICION_IVA
        {
            get
            {
                return _CONDICION_IVA;
            }
            set
            {
                OnCONDICION_IVAChanging(value);
                ReportPropertyChanging("CONDICION_IVA");
                _CONDICION_IVA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CONDICION_IVA");
                OnCONDICION_IVAChanged();
            }
        }
        private Nullable<global::System.Int32> _CONDICION_IVA;
        partial void OnCONDICION_IVAChanging(Nullable<global::System.Int32> value);
        partial void OnCONDICION_IVAChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_BENEFICIARIOS_T_ESTADOS_FK1", "T_ESTADOS")]
        public T_ESTADOS T_ESTADOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_ESTADOS>("GE.T_BENEFICIARIOS_T_ESTADOS_FK1", "T_ESTADOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_ESTADOS>("GE.T_BENEFICIARIOS_T_ESTADOS_FK1", "T_ESTADOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_ESTADOS> T_ESTADOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_ESTADOS>("GE.T_BENEFICIARIOS_T_ESTADOS_FK1", "T_ESTADOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_ESTADOS>("GE.T_BENEFICIARIOS_T_ESTADOS_FK1", "T_ESTADOS", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_BENEFICIARIOS_T_FICHAS_FK1", "T_FICHAS")]
        public T_FICHAS T_FICHAS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_FICHAS>("GE.T_BENEFICIARIOS_T_FICHAS_FK1", "T_FICHAS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_FICHAS>("GE.T_BENEFICIARIOS_T_FICHAS_FK1", "T_FICHAS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_FICHAS> T_FICHASReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_FICHAS>("GE.T_BENEFICIARIOS_T_FICHAS_FK1", "T_FICHAS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_FICHAS>("GE.T_BENEFICIARIOS_T_FICHAS_FK1", "T_FICHAS", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_CUENTAS_BANCO_T_BENEFIC_FK1", "T_CUENTAS_BANCO")]
        public EntityCollection<T_CUENTAS_BANCO> T_CUENTAS_BANCO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_CUENTAS_BANCO>("GE.T_CUENTAS_BANCO_T_BENEFIC_FK1", "T_CUENTAS_BANCO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_CUENTAS_BANCO>("GE.T_CUENTAS_BANCO_T_BENEFIC_FK1", "T_CUENTAS_BANCO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GE", Name="T_CUENTAS_BANCO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_CUENTAS_BANCO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto T_CUENTAS_BANCO.
        /// </summary>
        /// <param name="iD_CUENTA_BANCO">Valor inicial de la propiedad ID_CUENTA_BANCO.</param>
        /// <param name="iD_BENEFICIARIO">Valor inicial de la propiedad ID_BENEFICIARIO.</param>
        public static T_CUENTAS_BANCO CreateT_CUENTAS_BANCO(global::System.Int32 iD_CUENTA_BANCO, global::System.Int32 iD_BENEFICIARIO)
        {
            T_CUENTAS_BANCO t_CUENTAS_BANCO = new T_CUENTAS_BANCO();
            t_CUENTAS_BANCO.ID_CUENTA_BANCO = iD_CUENTA_BANCO;
            t_CUENTAS_BANCO.ID_BENEFICIARIO = iD_BENEFICIARIO;
            return t_CUENTAS_BANCO;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_CUENTA_BANCO
        {
            get
            {
                return _ID_CUENTA_BANCO;
            }
            set
            {
                if (_ID_CUENTA_BANCO != value)
                {
                    OnID_CUENTA_BANCOChanging(value);
                    ReportPropertyChanging("ID_CUENTA_BANCO");
                    _ID_CUENTA_BANCO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_CUENTA_BANCO");
                    OnID_CUENTA_BANCOChanged();
                }
            }
        }
        private global::System.Int32 _ID_CUENTA_BANCO;
        partial void OnID_CUENTA_BANCOChanging(global::System.Int32 value);
        partial void OnID_CUENTA_BANCOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_BENEFICIARIO
        {
            get
            {
                return _ID_BENEFICIARIO;
            }
            set
            {
                OnID_BENEFICIARIOChanging(value);
                ReportPropertyChanging("ID_BENEFICIARIO");
                _ID_BENEFICIARIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_BENEFICIARIO");
                OnID_BENEFICIARIOChanged();
            }
        }
        private global::System.Int32 _ID_BENEFICIARIO;
        partial void OnID_BENEFICIARIOChanging(global::System.Int32 value);
        partial void OnID_BENEFICIARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ID_SISTEMA
        {
            get
            {
                return _ID_SISTEMA;
            }
            set
            {
                OnID_SISTEMAChanging(value);
                ReportPropertyChanging("ID_SISTEMA");
                _ID_SISTEMA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_SISTEMA");
                OnID_SISTEMAChanged();
            }
        }
        private Nullable<global::System.Int16> _ID_SISTEMA;
        partial void OnID_SISTEMAChanging(Nullable<global::System.Int16> value);
        partial void OnID_SISTEMAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NRO_CTA
        {
            get
            {
                return _NRO_CTA;
            }
            set
            {
                OnNRO_CTAChanging(value);
                ReportPropertyChanging("NRO_CTA");
                _NRO_CTA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NRO_CTA");
                OnNRO_CTAChanged();
            }
        }
        private Nullable<global::System.Int32> _NRO_CTA;
        partial void OnNRO_CTAChanging(Nullable<global::System.Int32> value);
        partial void OnNRO_CTAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CBU
        {
            get
            {
                return _CBU;
            }
            set
            {
                OnCBUChanging(value);
                ReportPropertyChanging("CBU");
                _CBU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CBU");
                OnCBUChanged();
            }
        }
        private global::System.String _CBU;
        partial void OnCBUChanging(global::System.String value);
        partial void OnCBUChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USUARIO_BANCO
        {
            get
            {
                return _USUARIO_BANCO;
            }
            set
            {
                OnUSUARIO_BANCOChanging(value);
                ReportPropertyChanging("USUARIO_BANCO");
                _USUARIO_BANCO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USUARIO_BANCO");
                OnUSUARIO_BANCOChanged();
            }
        }
        private global::System.String _USUARIO_BANCO;
        partial void OnUSUARIO_BANCOChanging(global::System.String value);
        partial void OnUSUARIO_BANCOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ID_SUCURSAL
        {
            get
            {
                return _ID_SUCURSAL;
            }
            set
            {
                OnID_SUCURSALChanging(value);
                ReportPropertyChanging("ID_SUCURSAL");
                _ID_SUCURSAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_SUCURSAL");
                OnID_SUCURSALChanged();
            }
        }
        private Nullable<global::System.Int16> _ID_SUCURSAL;
        partial void OnID_SUCURSALChanging(Nullable<global::System.Int16> value);
        partial void OnID_SUCURSALChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ID_MONEDA
        {
            get
            {
                return _ID_MONEDA;
            }
            set
            {
                OnID_MONEDAChanging(value);
                ReportPropertyChanging("ID_MONEDA");
                _ID_MONEDA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_MONEDA");
                OnID_MONEDAChanged();
            }
        }
        private Nullable<global::System.Int16> _ID_MONEDA;
        partial void OnID_MONEDAChanging(Nullable<global::System.Int16> value);
        partial void OnID_MONEDAChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_CUENTAS_BANCO_T_BENEFIC_FK1", "T_BENEFICIARIOS")]
        public T_BENEFICIARIOS T_BENEFICIARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_BENEFICIARIOS>("GE.T_CUENTAS_BANCO_T_BENEFIC_FK1", "T_BENEFICIARIOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_BENEFICIARIOS>("GE.T_CUENTAS_BANCO_T_BENEFIC_FK1", "T_BENEFICIARIOS").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_BENEFICIARIOS> T_BENEFICIARIOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_BENEFICIARIOS>("GE.T_CUENTAS_BANCO_T_BENEFIC_FK1", "T_BENEFICIARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_BENEFICIARIOS>("GE.T_CUENTAS_BANCO_T_BENEFIC_FK1", "T_BENEFICIARIOS", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_CUENTAS_BANCO_MONEDA_FK", "T_TABLAS_BCO_CBA")]
        public T_TABLAS_BCO_CBA T_TABLAS_BCO_CBA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_TABLAS_BCO_CBA>("GE.T_CUENTAS_BANCO_MONEDA_FK", "T_TABLAS_BCO_CBA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_TABLAS_BCO_CBA>("GE.T_CUENTAS_BANCO_MONEDA_FK", "T_TABLAS_BCO_CBA").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_TABLAS_BCO_CBA> T_TABLAS_BCO_CBAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_TABLAS_BCO_CBA>("GE.T_CUENTAS_BANCO_MONEDA_FK", "T_TABLAS_BCO_CBA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_TABLAS_BCO_CBA>("GE.T_CUENTAS_BANCO_MONEDA_FK", "T_TABLAS_BCO_CBA", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_CUENTAS_BANCO_SISTEMAFK1", "T_TABLAS_BCO_CBA")]
        public T_TABLAS_BCO_CBA T_TABLAS_BCO_CBA1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_TABLAS_BCO_CBA>("GE.T_CUENTAS_BANCO_SISTEMAFK1", "T_TABLAS_BCO_CBA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_TABLAS_BCO_CBA>("GE.T_CUENTAS_BANCO_SISTEMAFK1", "T_TABLAS_BCO_CBA").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_TABLAS_BCO_CBA> T_TABLAS_BCO_CBA1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_TABLAS_BCO_CBA>("GE.T_CUENTAS_BANCO_SISTEMAFK1", "T_TABLAS_BCO_CBA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_TABLAS_BCO_CBA>("GE.T_CUENTAS_BANCO_SISTEMAFK1", "T_TABLAS_BCO_CBA", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_CUENTAS_BANCO_SUCURSAL__FK1", "T_TABLAS_BCO_CBA")]
        public T_TABLAS_BCO_CBA T_TABLAS_BCO_CBA2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_TABLAS_BCO_CBA>("GE.T_CUENTAS_BANCO_SUCURSAL__FK1", "T_TABLAS_BCO_CBA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_TABLAS_BCO_CBA>("GE.T_CUENTAS_BANCO_SUCURSAL__FK1", "T_TABLAS_BCO_CBA").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_TABLAS_BCO_CBA> T_TABLAS_BCO_CBA2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_TABLAS_BCO_CBA>("GE.T_CUENTAS_BANCO_SUCURSAL__FK1", "T_TABLAS_BCO_CBA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_TABLAS_BCO_CBA>("GE.T_CUENTAS_BANCO_SUCURSAL__FK1", "T_TABLAS_BCO_CBA", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GE", Name="T_ESTADOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_ESTADOS : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto T_ESTADOS.
        /// </summary>
        /// <param name="iD_ESTADO">Valor inicial de la propiedad ID_ESTADO.</param>
        public static T_ESTADOS CreateT_ESTADOS(global::System.Int16 iD_ESTADO)
        {
            T_ESTADOS t_ESTADOS = new T_ESTADOS();
            t_ESTADOS.ID_ESTADO = iD_ESTADO;
            return t_ESTADOS;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ID_ESTADO
        {
            get
            {
                return _ID_ESTADO;
            }
            set
            {
                if (_ID_ESTADO != value)
                {
                    OnID_ESTADOChanging(value);
                    ReportPropertyChanging("ID_ESTADO");
                    _ID_ESTADO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_ESTADO");
                    OnID_ESTADOChanged();
                }
            }
        }
        private global::System.Int16 _ID_ESTADO;
        partial void OnID_ESTADOChanging(global::System.Int16 value);
        partial void OnID_ESTADOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String N_ESTADO
        {
            get
            {
                return _N_ESTADO;
            }
            set
            {
                OnN_ESTADOChanging(value);
                ReportPropertyChanging("N_ESTADO");
                _N_ESTADO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("N_ESTADO");
                OnN_ESTADOChanged();
            }
        }
        private global::System.String _N_ESTADO;
        partial void OnN_ESTADOChanging(global::System.String value);
        partial void OnN_ESTADOChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_BENEFICIARIOS_T_ESTADOS_FK1", "T_BENEFICIARIOS")]
        public EntityCollection<T_BENEFICIARIOS> T_BENEFICIARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_BENEFICIARIOS>("GE.T_BENEFICIARIOS_T_ESTADOS_FK1", "T_BENEFICIARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_BENEFICIARIOS>("GE.T_BENEFICIARIOS_T_ESTADOS_FK1", "T_BENEFICIARIOS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GE", Name="T_FICHAS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_FICHAS : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto T_FICHAS.
        /// </summary>
        /// <param name="iD_FICHA">Valor inicial de la propiedad ID_FICHA.</param>
        /// <param name="cUIL">Valor inicial de la propiedad CUIL.</param>
        /// <param name="aPELLIDO">Valor inicial de la propiedad APELLIDO.</param>
        /// <param name="nOMBRE">Valor inicial de la propiedad NOMBRE.</param>
        /// <param name="fER_NAC">Valor inicial de la propiedad FER_NAC.</param>
        /// <param name="tIPO_DOCUMENTO">Valor inicial de la propiedad TIPO_DOCUMENTO.</param>
        /// <param name="nUMERO_DOCUMENTO">Valor inicial de la propiedad NUMERO_DOCUMENTO.</param>
        /// <param name="bARRIO">Valor inicial de la propiedad BARRIO.</param>
        /// <param name="cODIGO_POSTAL">Valor inicial de la propiedad CODIGO_POSTAL.</param>
        /// <param name="mAIL">Valor inicial de la propiedad MAIL.</param>
        /// <param name="tIENE_HIJOS">Valor inicial de la propiedad TIENE_HIJOS.</param>
        /// <param name="cANTIDAD_HIJOS">Valor inicial de la propiedad CANTIDAD_HIJOS.</param>
        /// <param name="eS_DISCAPACITADO">Valor inicial de la propiedad ES_DISCAPACITADO.</param>
        /// <param name="tIENE_DEF_MOTORA">Valor inicial de la propiedad TIENE_DEF_MOTORA.</param>
        /// <param name="tIENE_DEF_MENTAL">Valor inicial de la propiedad TIENE_DEF_MENTAL.</param>
        /// <param name="tIENE_DEF_SENSORIAL">Valor inicial de la propiedad TIENE_DEF_SENSORIAL.</param>
        /// <param name="tIENE_DEF_PSICOLOGICA">Valor inicial de la propiedad TIENE_DEF_PSICOLOGICA.</param>
        /// <param name="sEXO">Valor inicial de la propiedad SEXO.</param>
        /// <param name="tIPO_FICHA">Valor inicial de la propiedad TIPO_FICHA.</param>
        /// <param name="eSTADO_CIVIL">Valor inicial de la propiedad ESTADO_CIVIL.</param>
        /// <param name="cODIGO_SEGURIDAD">Valor inicial de la propiedad CODIGO_SEGURIDAD.</param>
        public static T_FICHAS CreateT_FICHAS(global::System.Int32 iD_FICHA, global::System.String cUIL, global::System.String aPELLIDO, global::System.String nOMBRE, global::System.DateTime fER_NAC, global::System.Int32 tIPO_DOCUMENTO, global::System.String nUMERO_DOCUMENTO, global::System.String bARRIO, global::System.String cODIGO_POSTAL, global::System.String mAIL, global::System.String tIENE_HIJOS, global::System.Int32 cANTIDAD_HIJOS, global::System.String eS_DISCAPACITADO, global::System.String tIENE_DEF_MOTORA, global::System.String tIENE_DEF_MENTAL, global::System.String tIENE_DEF_SENSORIAL, global::System.String tIENE_DEF_PSICOLOGICA, global::System.String sEXO, global::System.Int32 tIPO_FICHA, global::System.Int32 eSTADO_CIVIL, global::System.String cODIGO_SEGURIDAD)
        {
            T_FICHAS t_FICHAS = new T_FICHAS();
            t_FICHAS.ID_FICHA = iD_FICHA;
            t_FICHAS.CUIL = cUIL;
            t_FICHAS.APELLIDO = aPELLIDO;
            t_FICHAS.NOMBRE = nOMBRE;
            t_FICHAS.FER_NAC = fER_NAC;
            t_FICHAS.TIPO_DOCUMENTO = tIPO_DOCUMENTO;
            t_FICHAS.NUMERO_DOCUMENTO = nUMERO_DOCUMENTO;
            t_FICHAS.BARRIO = bARRIO;
            t_FICHAS.CODIGO_POSTAL = cODIGO_POSTAL;
            t_FICHAS.MAIL = mAIL;
            t_FICHAS.TIENE_HIJOS = tIENE_HIJOS;
            t_FICHAS.CANTIDAD_HIJOS = cANTIDAD_HIJOS;
            t_FICHAS.ES_DISCAPACITADO = eS_DISCAPACITADO;
            t_FICHAS.TIENE_DEF_MOTORA = tIENE_DEF_MOTORA;
            t_FICHAS.TIENE_DEF_MENTAL = tIENE_DEF_MENTAL;
            t_FICHAS.TIENE_DEF_SENSORIAL = tIENE_DEF_SENSORIAL;
            t_FICHAS.TIENE_DEF_PSICOLOGICA = tIENE_DEF_PSICOLOGICA;
            t_FICHAS.SEXO = sEXO;
            t_FICHAS.TIPO_FICHA = tIPO_FICHA;
            t_FICHAS.ESTADO_CIVIL = eSTADO_CIVIL;
            t_FICHAS.CODIGO_SEGURIDAD = cODIGO_SEGURIDAD;
            return t_FICHAS;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_FICHA
        {
            get
            {
                return _ID_FICHA;
            }
            set
            {
                if (_ID_FICHA != value)
                {
                    OnID_FICHAChanging(value);
                    ReportPropertyChanging("ID_FICHA");
                    _ID_FICHA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_FICHA");
                    OnID_FICHAChanged();
                }
            }
        }
        private global::System.Int32 _ID_FICHA;
        partial void OnID_FICHAChanging(global::System.Int32 value);
        partial void OnID_FICHAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CUIL
        {
            get
            {
                return _CUIL;
            }
            set
            {
                OnCUILChanging(value);
                ReportPropertyChanging("CUIL");
                _CUIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CUIL");
                OnCUILChanged();
            }
        }
        private global::System.String _CUIL;
        partial void OnCUILChanging(global::System.String value);
        partial void OnCUILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String APELLIDO
        {
            get
            {
                return _APELLIDO;
            }
            set
            {
                OnAPELLIDOChanging(value);
                ReportPropertyChanging("APELLIDO");
                _APELLIDO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("APELLIDO");
                OnAPELLIDOChanged();
            }
        }
        private global::System.String _APELLIDO;
        partial void OnAPELLIDOChanging(global::System.String value);
        partial void OnAPELLIDOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FER_NAC
        {
            get
            {
                return _FER_NAC;
            }
            set
            {
                OnFER_NACChanging(value);
                ReportPropertyChanging("FER_NAC");
                _FER_NAC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FER_NAC");
                OnFER_NACChanged();
            }
        }
        private global::System.DateTime _FER_NAC;
        partial void OnFER_NACChanging(global::System.DateTime value);
        partial void OnFER_NACChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TIPO_DOCUMENTO
        {
            get
            {
                return _TIPO_DOCUMENTO;
            }
            set
            {
                OnTIPO_DOCUMENTOChanging(value);
                ReportPropertyChanging("TIPO_DOCUMENTO");
                _TIPO_DOCUMENTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TIPO_DOCUMENTO");
                OnTIPO_DOCUMENTOChanged();
            }
        }
        private global::System.Int32 _TIPO_DOCUMENTO;
        partial void OnTIPO_DOCUMENTOChanging(global::System.Int32 value);
        partial void OnTIPO_DOCUMENTOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NUMERO_DOCUMENTO
        {
            get
            {
                return _NUMERO_DOCUMENTO;
            }
            set
            {
                OnNUMERO_DOCUMENTOChanging(value);
                ReportPropertyChanging("NUMERO_DOCUMENTO");
                _NUMERO_DOCUMENTO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NUMERO_DOCUMENTO");
                OnNUMERO_DOCUMENTOChanged();
            }
        }
        private global::System.String _NUMERO_DOCUMENTO;
        partial void OnNUMERO_DOCUMENTOChanging(global::System.String value);
        partial void OnNUMERO_DOCUMENTOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CALLE
        {
            get
            {
                return _CALLE;
            }
            set
            {
                OnCALLEChanging(value);
                ReportPropertyChanging("CALLE");
                _CALLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CALLE");
                OnCALLEChanged();
            }
        }
        private global::System.String _CALLE;
        partial void OnCALLEChanging(global::System.String value);
        partial void OnCALLEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NUMERO
        {
            get
            {
                return _NUMERO;
            }
            set
            {
                OnNUMEROChanging(value);
                ReportPropertyChanging("NUMERO");
                _NUMERO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NUMERO");
                OnNUMEROChanged();
            }
        }
        private global::System.String _NUMERO;
        partial void OnNUMEROChanging(global::System.String value);
        partial void OnNUMEROChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PISO
        {
            get
            {
                return _PISO;
            }
            set
            {
                OnPISOChanging(value);
                ReportPropertyChanging("PISO");
                _PISO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PISO");
                OnPISOChanged();
            }
        }
        private global::System.String _PISO;
        partial void OnPISOChanging(global::System.String value);
        partial void OnPISOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DPTO
        {
            get
            {
                return _DPTO;
            }
            set
            {
                OnDPTOChanging(value);
                ReportPropertyChanging("DPTO");
                _DPTO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DPTO");
                OnDPTOChanged();
            }
        }
        private global::System.String _DPTO;
        partial void OnDPTOChanging(global::System.String value);
        partial void OnDPTOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MONOBLOCK
        {
            get
            {
                return _MONOBLOCK;
            }
            set
            {
                OnMONOBLOCKChanging(value);
                ReportPropertyChanging("MONOBLOCK");
                _MONOBLOCK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MONOBLOCK");
                OnMONOBLOCKChanged();
            }
        }
        private global::System.String _MONOBLOCK;
        partial void OnMONOBLOCKChanging(global::System.String value);
        partial void OnMONOBLOCKChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARCELA
        {
            get
            {
                return _PARCELA;
            }
            set
            {
                OnPARCELAChanging(value);
                ReportPropertyChanging("PARCELA");
                _PARCELA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARCELA");
                OnPARCELAChanged();
            }
        }
        private global::System.String _PARCELA;
        partial void OnPARCELAChanging(global::System.String value);
        partial void OnPARCELAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MANZANA
        {
            get
            {
                return _MANZANA;
            }
            set
            {
                OnMANZANAChanging(value);
                ReportPropertyChanging("MANZANA");
                _MANZANA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MANZANA");
                OnMANZANAChanged();
            }
        }
        private global::System.String _MANZANA;
        partial void OnMANZANAChanging(global::System.String value);
        partial void OnMANZANAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ENTRECALLES
        {
            get
            {
                return _ENTRECALLES;
            }
            set
            {
                OnENTRECALLESChanging(value);
                ReportPropertyChanging("ENTRECALLES");
                _ENTRECALLES = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ENTRECALLES");
                OnENTRECALLESChanged();
            }
        }
        private global::System.String _ENTRECALLES;
        partial void OnENTRECALLESChanging(global::System.String value);
        partial void OnENTRECALLESChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BARRIO
        {
            get
            {
                return _BARRIO;
            }
            set
            {
                OnBARRIOChanging(value);
                ReportPropertyChanging("BARRIO");
                _BARRIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BARRIO");
                OnBARRIOChanged();
            }
        }
        private global::System.String _BARRIO;
        partial void OnBARRIOChanging(global::System.String value);
        partial void OnBARRIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CODIGO_POSTAL
        {
            get
            {
                return _CODIGO_POSTAL;
            }
            set
            {
                OnCODIGO_POSTALChanging(value);
                ReportPropertyChanging("CODIGO_POSTAL");
                _CODIGO_POSTAL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CODIGO_POSTAL");
                OnCODIGO_POSTALChanged();
            }
        }
        private global::System.String _CODIGO_POSTAL;
        partial void OnCODIGO_POSTALChanging(global::System.String value);
        partial void OnCODIGO_POSTALChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_LOCALIDAD
        {
            get
            {
                return _ID_LOCALIDAD;
            }
            set
            {
                OnID_LOCALIDADChanging(value);
                ReportPropertyChanging("ID_LOCALIDAD");
                _ID_LOCALIDAD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_LOCALIDAD");
                OnID_LOCALIDADChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_LOCALIDAD;
        partial void OnID_LOCALIDADChanging(Nullable<global::System.Int32> value);
        partial void OnID_LOCALIDADChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TEL_FIJO
        {
            get
            {
                return _TEL_FIJO;
            }
            set
            {
                OnTEL_FIJOChanging(value);
                ReportPropertyChanging("TEL_FIJO");
                _TEL_FIJO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEL_FIJO");
                OnTEL_FIJOChanged();
            }
        }
        private global::System.String _TEL_FIJO;
        partial void OnTEL_FIJOChanging(global::System.String value);
        partial void OnTEL_FIJOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TEL_CELULAR
        {
            get
            {
                return _TEL_CELULAR;
            }
            set
            {
                OnTEL_CELULARChanging(value);
                ReportPropertyChanging("TEL_CELULAR");
                _TEL_CELULAR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEL_CELULAR");
                OnTEL_CELULARChanged();
            }
        }
        private global::System.String _TEL_CELULAR;
        partial void OnTEL_CELULARChanging(global::System.String value);
        partial void OnTEL_CELULARChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CONTACTO
        {
            get
            {
                return _CONTACTO;
            }
            set
            {
                OnCONTACTOChanging(value);
                ReportPropertyChanging("CONTACTO");
                _CONTACTO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CONTACTO");
                OnCONTACTOChanged();
            }
        }
        private global::System.String _CONTACTO;
        partial void OnCONTACTOChanging(global::System.String value);
        partial void OnCONTACTOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAIL
        {
            get
            {
                return _MAIL;
            }
            set
            {
                OnMAILChanging(value);
                ReportPropertyChanging("MAIL");
                _MAIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MAIL");
                OnMAILChanged();
            }
        }
        private global::System.String _MAIL;
        partial void OnMAILChanging(global::System.String value);
        partial void OnMAILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIENE_HIJOS
        {
            get
            {
                return _TIENE_HIJOS;
            }
            set
            {
                OnTIENE_HIJOSChanging(value);
                ReportPropertyChanging("TIENE_HIJOS");
                _TIENE_HIJOS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIENE_HIJOS");
                OnTIENE_HIJOSChanged();
            }
        }
        private global::System.String _TIENE_HIJOS;
        partial void OnTIENE_HIJOSChanging(global::System.String value);
        partial void OnTIENE_HIJOSChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CANTIDAD_HIJOS
        {
            get
            {
                return _CANTIDAD_HIJOS;
            }
            set
            {
                OnCANTIDAD_HIJOSChanging(value);
                ReportPropertyChanging("CANTIDAD_HIJOS");
                _CANTIDAD_HIJOS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CANTIDAD_HIJOS");
                OnCANTIDAD_HIJOSChanged();
            }
        }
        private global::System.Int32 _CANTIDAD_HIJOS;
        partial void OnCANTIDAD_HIJOSChanging(global::System.Int32 value);
        partial void OnCANTIDAD_HIJOSChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ES_DISCAPACITADO
        {
            get
            {
                return _ES_DISCAPACITADO;
            }
            set
            {
                OnES_DISCAPACITADOChanging(value);
                ReportPropertyChanging("ES_DISCAPACITADO");
                _ES_DISCAPACITADO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ES_DISCAPACITADO");
                OnES_DISCAPACITADOChanged();
            }
        }
        private global::System.String _ES_DISCAPACITADO;
        partial void OnES_DISCAPACITADOChanging(global::System.String value);
        partial void OnES_DISCAPACITADOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIENE_DEF_MOTORA
        {
            get
            {
                return _TIENE_DEF_MOTORA;
            }
            set
            {
                OnTIENE_DEF_MOTORAChanging(value);
                ReportPropertyChanging("TIENE_DEF_MOTORA");
                _TIENE_DEF_MOTORA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIENE_DEF_MOTORA");
                OnTIENE_DEF_MOTORAChanged();
            }
        }
        private global::System.String _TIENE_DEF_MOTORA;
        partial void OnTIENE_DEF_MOTORAChanging(global::System.String value);
        partial void OnTIENE_DEF_MOTORAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIENE_DEF_MENTAL
        {
            get
            {
                return _TIENE_DEF_MENTAL;
            }
            set
            {
                OnTIENE_DEF_MENTALChanging(value);
                ReportPropertyChanging("TIENE_DEF_MENTAL");
                _TIENE_DEF_MENTAL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIENE_DEF_MENTAL");
                OnTIENE_DEF_MENTALChanged();
            }
        }
        private global::System.String _TIENE_DEF_MENTAL;
        partial void OnTIENE_DEF_MENTALChanging(global::System.String value);
        partial void OnTIENE_DEF_MENTALChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIENE_DEF_SENSORIAL
        {
            get
            {
                return _TIENE_DEF_SENSORIAL;
            }
            set
            {
                OnTIENE_DEF_SENSORIALChanging(value);
                ReportPropertyChanging("TIENE_DEF_SENSORIAL");
                _TIENE_DEF_SENSORIAL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIENE_DEF_SENSORIAL");
                OnTIENE_DEF_SENSORIALChanged();
            }
        }
        private global::System.String _TIENE_DEF_SENSORIAL;
        partial void OnTIENE_DEF_SENSORIALChanging(global::System.String value);
        partial void OnTIENE_DEF_SENSORIALChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIENE_DEF_PSICOLOGICA
        {
            get
            {
                return _TIENE_DEF_PSICOLOGICA;
            }
            set
            {
                OnTIENE_DEF_PSICOLOGICAChanging(value);
                ReportPropertyChanging("TIENE_DEF_PSICOLOGICA");
                _TIENE_DEF_PSICOLOGICA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIENE_DEF_PSICOLOGICA");
                OnTIENE_DEF_PSICOLOGICAChanged();
            }
        }
        private global::System.String _TIENE_DEF_PSICOLOGICA;
        partial void OnTIENE_DEF_PSICOLOGICAChanging(global::System.String value);
        partial void OnTIENE_DEF_PSICOLOGICAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEFICIENCIA_OTRA
        {
            get
            {
                return _DEFICIENCIA_OTRA;
            }
            set
            {
                OnDEFICIENCIA_OTRAChanging(value);
                ReportPropertyChanging("DEFICIENCIA_OTRA");
                _DEFICIENCIA_OTRA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEFICIENCIA_OTRA");
                OnDEFICIENCIA_OTRAChanged();
            }
        }
        private global::System.String _DEFICIENCIA_OTRA;
        partial void OnDEFICIENCIA_OTRAChanging(global::System.String value);
        partial void OnDEFICIENCIA_OTRAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SEXO
        {
            get
            {
                return _SEXO;
            }
            set
            {
                OnSEXOChanging(value);
                ReportPropertyChanging("SEXO");
                _SEXO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SEXO");
                OnSEXOChanged();
            }
        }
        private global::System.String _SEXO;
        partial void OnSEXOChanging(global::System.String value);
        partial void OnSEXOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TIPO_FICHA
        {
            get
            {
                return _TIPO_FICHA;
            }
            set
            {
                OnTIPO_FICHAChanging(value);
                ReportPropertyChanging("TIPO_FICHA");
                _TIPO_FICHA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TIPO_FICHA");
                OnTIPO_FICHAChanged();
            }
        }
        private global::System.Int32 _TIPO_FICHA;
        partial void OnTIPO_FICHAChanging(global::System.Int32 value);
        partial void OnTIPO_FICHAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ESTADO_CIVIL
        {
            get
            {
                return _ESTADO_CIVIL;
            }
            set
            {
                OnESTADO_CIVILChanging(value);
                ReportPropertyChanging("ESTADO_CIVIL");
                _ESTADO_CIVIL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ESTADO_CIVIL");
                OnESTADO_CIVILChanged();
            }
        }
        private global::System.Int32 _ESTADO_CIVIL;
        partial void OnESTADO_CIVILChanging(global::System.Int32 value);
        partial void OnESTADO_CIVILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CODIGO_SEGURIDAD
        {
            get
            {
                return _CODIGO_SEGURIDAD;
            }
            set
            {
                OnCODIGO_SEGURIDADChanging(value);
                ReportPropertyChanging("CODIGO_SEGURIDAD");
                _CODIGO_SEGURIDAD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CODIGO_SEGURIDAD");
                OnCODIGO_SEGURIDADChanged();
            }
        }
        private global::System.String _CODIGO_SEGURIDAD;
        partial void OnCODIGO_SEGURIDADChanging(global::System.String value);
        partial void OnCODIGO_SEGURIDADChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FEC_ALTA
        {
            get
            {
                return _FEC_ALTA;
            }
            set
            {
                OnFEC_ALTAChanging(value);
                ReportPropertyChanging("FEC_ALTA");
                _FEC_ALTA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FEC_ALTA");
                OnFEC_ALTAChanged();
            }
        }
        private Nullable<global::System.DateTime> _FEC_ALTA;
        partial void OnFEC_ALTAChanging(Nullable<global::System.DateTime> value);
        partial void OnFEC_ALTAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USUARIO_ALTA
        {
            get
            {
                return _USUARIO_ALTA;
            }
            set
            {
                OnUSUARIO_ALTAChanging(value);
                ReportPropertyChanging("USUARIO_ALTA");
                _USUARIO_ALTA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USUARIO_ALTA");
                OnUSUARIO_ALTAChanged();
            }
        }
        private global::System.String _USUARIO_ALTA;
        partial void OnUSUARIO_ALTAChanging(global::System.String value);
        partial void OnUSUARIO_ALTAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FEC_MODIF
        {
            get
            {
                return _FEC_MODIF;
            }
            set
            {
                OnFEC_MODIFChanging(value);
                ReportPropertyChanging("FEC_MODIF");
                _FEC_MODIF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FEC_MODIF");
                OnFEC_MODIFChanged();
            }
        }
        private Nullable<global::System.DateTime> _FEC_MODIF;
        partial void OnFEC_MODIFChanging(Nullable<global::System.DateTime> value);
        partial void OnFEC_MODIFChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USUARIO_MODIF
        {
            get
            {
                return _USUARIO_MODIF;
            }
            set
            {
                OnUSUARIO_MODIFChanging(value);
                ReportPropertyChanging("USUARIO_MODIF");
                _USUARIO_MODIF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USUARIO_MODIF");
                OnUSUARIO_MODIFChanged();
            }
        }
        private global::System.String _USUARIO_MODIF;
        partial void OnUSUARIO_MODIFChanging(global::System.String value);
        partial void OnUSUARIO_MODIFChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ORIGEN_CARGA
        {
            get
            {
                return _ORIGEN_CARGA;
            }
            set
            {
                OnORIGEN_CARGAChanging(value);
                ReportPropertyChanging("ORIGEN_CARGA");
                _ORIGEN_CARGA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ORIGEN_CARGA");
                OnORIGEN_CARGAChanged();
            }
        }
        private global::System.String _ORIGEN_CARGA;
        partial void OnORIGEN_CARGAChanging(global::System.String value);
        partial void OnORIGEN_CARGAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NRO_TRAMITE
        {
            get
            {
                return _NRO_TRAMITE;
            }
            set
            {
                OnNRO_TRAMITEChanging(value);
                ReportPropertyChanging("NRO_TRAMITE");
                _NRO_TRAMITE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NRO_TRAMITE");
                OnNRO_TRAMITEChanged();
            }
        }
        private global::System.String _NRO_TRAMITE;
        partial void OnNRO_TRAMITEChanging(global::System.String value);
        partial void OnNRO_TRAMITEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_ESTADO_FICHA
        {
            get
            {
                return _ID_ESTADO_FICHA;
            }
            set
            {
                OnID_ESTADO_FICHAChanging(value);
                ReportPropertyChanging("ID_ESTADO_FICHA");
                _ID_ESTADO_FICHA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_ESTADO_FICHA");
                OnID_ESTADO_FICHAChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_ESTADO_FICHA;
        partial void OnID_ESTADO_FICHAChanging(Nullable<global::System.Int32> value);
        partial void OnID_ESTADO_FICHAChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_BENEFICIARIOS_T_FICHAS_FK1", "T_BENEFICIARIOS")]
        public EntityCollection<T_BENEFICIARIOS> T_BENEFICIARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_BENEFICIARIOS>("GE.T_BENEFICIARIOS_T_FICHAS_FK1", "T_BENEFICIARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_BENEFICIARIOS>("GE.T_BENEFICIARIOS_T_FICHAS_FK1", "T_BENEFICIARIOS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GE", Name="T_TABLAS_BCO_CBA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_TABLAS_BCO_CBA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto T_TABLAS_BCO_CBA.
        /// </summary>
        /// <param name="iD_TABLA_BCO_CBA">Valor inicial de la propiedad ID_TABLA_BCO_CBA.</param>
        public static T_TABLAS_BCO_CBA CreateT_TABLAS_BCO_CBA(global::System.Int16 iD_TABLA_BCO_CBA)
        {
            T_TABLAS_BCO_CBA t_TABLAS_BCO_CBA = new T_TABLAS_BCO_CBA();
            t_TABLAS_BCO_CBA.ID_TABLA_BCO_CBA = iD_TABLA_BCO_CBA;
            return t_TABLAS_BCO_CBA;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ID_TABLA_BCO_CBA
        {
            get
            {
                return _ID_TABLA_BCO_CBA;
            }
            set
            {
                if (_ID_TABLA_BCO_CBA != value)
                {
                    OnID_TABLA_BCO_CBAChanging(value);
                    ReportPropertyChanging("ID_TABLA_BCO_CBA");
                    _ID_TABLA_BCO_CBA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_TABLA_BCO_CBA");
                    OnID_TABLA_BCO_CBAChanged();
                }
            }
        }
        private global::System.Int16 _ID_TABLA_BCO_CBA;
        partial void OnID_TABLA_BCO_CBAChanging(global::System.Int16 value);
        partial void OnID_TABLA_BCO_CBAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COD_BCO_CBA
        {
            get
            {
                return _COD_BCO_CBA;
            }
            set
            {
                OnCOD_BCO_CBAChanging(value);
                ReportPropertyChanging("COD_BCO_CBA");
                _COD_BCO_CBA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COD_BCO_CBA");
                OnCOD_BCO_CBAChanged();
            }
        }
        private global::System.String _COD_BCO_CBA;
        partial void OnCOD_BCO_CBAChanging(global::System.String value);
        partial void OnCOD_BCO_CBAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPCION
        {
            get
            {
                return _DESCRIPCION;
            }
            set
            {
                OnDESCRIPCIONChanging(value);
                ReportPropertyChanging("DESCRIPCION");
                _DESCRIPCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPCION");
                OnDESCRIPCIONChanged();
            }
        }
        private global::System.String _DESCRIPCION;
        partial void OnDESCRIPCIONChanging(global::System.String value);
        partial void OnDESCRIPCIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ID_TIPO_TABLA_BCO_CBA
        {
            get
            {
                return _ID_TIPO_TABLA_BCO_CBA;
            }
            set
            {
                OnID_TIPO_TABLA_BCO_CBAChanging(value);
                ReportPropertyChanging("ID_TIPO_TABLA_BCO_CBA");
                _ID_TIPO_TABLA_BCO_CBA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_TIPO_TABLA_BCO_CBA");
                OnID_TIPO_TABLA_BCO_CBAChanged();
            }
        }
        private Nullable<global::System.Int16> _ID_TIPO_TABLA_BCO_CBA;
        partial void OnID_TIPO_TABLA_BCO_CBAChanging(Nullable<global::System.Int16> value);
        partial void OnID_TIPO_TABLA_BCO_CBAChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_CUENTAS_BANCO_MONEDA_FK", "T_CUENTAS_BANCO")]
        public EntityCollection<T_CUENTAS_BANCO> T_CUENTAS_BANCO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_CUENTAS_BANCO>("GE.T_CUENTAS_BANCO_MONEDA_FK", "T_CUENTAS_BANCO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_CUENTAS_BANCO>("GE.T_CUENTAS_BANCO_MONEDA_FK", "T_CUENTAS_BANCO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_CUENTAS_BANCO_SISTEMAFK1", "T_CUENTAS_BANCO")]
        public EntityCollection<T_CUENTAS_BANCO> T_CUENTAS_BANCO1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_CUENTAS_BANCO>("GE.T_CUENTAS_BANCO_SISTEMAFK1", "T_CUENTAS_BANCO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_CUENTAS_BANCO>("GE.T_CUENTAS_BANCO_SISTEMAFK1", "T_CUENTAS_BANCO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_CUENTAS_BANCO_SUCURSAL__FK1", "T_CUENTAS_BANCO")]
        public EntityCollection<T_CUENTAS_BANCO> T_CUENTAS_BANCO2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_CUENTAS_BANCO>("GE.T_CUENTAS_BANCO_SUCURSAL__FK1", "T_CUENTAS_BANCO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_CUENTAS_BANCO>("GE.T_CUENTAS_BANCO_SUCURSAL__FK1", "T_CUENTAS_BANCO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_TABLAS_BCO_CBA_T_TIPOS__FK1", "T_TIPOS_TABLA_BCO_CBA")]
        public T_TIPOS_TABLA_BCO_CBA T_TIPOS_TABLA_BCO_CBA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_TIPOS_TABLA_BCO_CBA>("GE.T_TABLAS_BCO_CBA_T_TIPOS__FK1", "T_TIPOS_TABLA_BCO_CBA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_TIPOS_TABLA_BCO_CBA>("GE.T_TABLAS_BCO_CBA_T_TIPOS__FK1", "T_TIPOS_TABLA_BCO_CBA").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_TIPOS_TABLA_BCO_CBA> T_TIPOS_TABLA_BCO_CBAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_TIPOS_TABLA_BCO_CBA>("GE.T_TABLAS_BCO_CBA_T_TIPOS__FK1", "T_TIPOS_TABLA_BCO_CBA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_TIPOS_TABLA_BCO_CBA>("GE.T_TABLAS_BCO_CBA_T_TIPOS__FK1", "T_TIPOS_TABLA_BCO_CBA", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GE", Name="T_TIPOS_TABLA_BCO_CBA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_TIPOS_TABLA_BCO_CBA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto T_TIPOS_TABLA_BCO_CBA.
        /// </summary>
        /// <param name="iD_TIPO_TABLA_BCO_CBA">Valor inicial de la propiedad ID_TIPO_TABLA_BCO_CBA.</param>
        /// <param name="n_TIPO_TABLA_BCO_CBA">Valor inicial de la propiedad N_TIPO_TABLA_BCO_CBA.</param>
        public static T_TIPOS_TABLA_BCO_CBA CreateT_TIPOS_TABLA_BCO_CBA(global::System.Int16 iD_TIPO_TABLA_BCO_CBA, global::System.String n_TIPO_TABLA_BCO_CBA)
        {
            T_TIPOS_TABLA_BCO_CBA t_TIPOS_TABLA_BCO_CBA = new T_TIPOS_TABLA_BCO_CBA();
            t_TIPOS_TABLA_BCO_CBA.ID_TIPO_TABLA_BCO_CBA = iD_TIPO_TABLA_BCO_CBA;
            t_TIPOS_TABLA_BCO_CBA.N_TIPO_TABLA_BCO_CBA = n_TIPO_TABLA_BCO_CBA;
            return t_TIPOS_TABLA_BCO_CBA;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ID_TIPO_TABLA_BCO_CBA
        {
            get
            {
                return _ID_TIPO_TABLA_BCO_CBA;
            }
            set
            {
                if (_ID_TIPO_TABLA_BCO_CBA != value)
                {
                    OnID_TIPO_TABLA_BCO_CBAChanging(value);
                    ReportPropertyChanging("ID_TIPO_TABLA_BCO_CBA");
                    _ID_TIPO_TABLA_BCO_CBA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_TIPO_TABLA_BCO_CBA");
                    OnID_TIPO_TABLA_BCO_CBAChanged();
                }
            }
        }
        private global::System.Int16 _ID_TIPO_TABLA_BCO_CBA;
        partial void OnID_TIPO_TABLA_BCO_CBAChanging(global::System.Int16 value);
        partial void OnID_TIPO_TABLA_BCO_CBAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String N_TIPO_TABLA_BCO_CBA
        {
            get
            {
                return _N_TIPO_TABLA_BCO_CBA;
            }
            set
            {
                OnN_TIPO_TABLA_BCO_CBAChanging(value);
                ReportPropertyChanging("N_TIPO_TABLA_BCO_CBA");
                _N_TIPO_TABLA_BCO_CBA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("N_TIPO_TABLA_BCO_CBA");
                OnN_TIPO_TABLA_BCO_CBAChanged();
            }
        }
        private global::System.String _N_TIPO_TABLA_BCO_CBA;
        partial void OnN_TIPO_TABLA_BCO_CBAChanging(global::System.String value);
        partial void OnN_TIPO_TABLA_BCO_CBAChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GE", "T_TABLAS_BCO_CBA_T_TIPOS__FK1", "T_TABLAS_BCO_CBA")]
        public EntityCollection<T_TABLAS_BCO_CBA> T_TABLAS_BCO_CBA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_TABLAS_BCO_CBA>("GE.T_TABLAS_BCO_CBA_T_TIPOS__FK1", "T_TABLAS_BCO_CBA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_TABLAS_BCO_CBA>("GE.T_TABLAS_BCO_CBA_T_TIPOS__FK1", "T_TABLAS_BCO_CBA", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
